### ISSUE TITLE
Timestamp request expired - 50102

### ISSUE THREAD

**Issue by javedwahid** [burakoner/OKX.Api#73]
This just started today.  When using the Rest client Trade.PlaceOrderAsync() to place an order, I'm getting a response back of: Code = 50102, Message = Timestamp request expired, Data = null.

I was using v2.4.8.  I upgraded to the latest version 5.4.1217.  But I'm still receiving the same issue.  Not sure what happened.  I was able to place Orders yesterday without any issues.  

I really have no clue how to fix this on my own.  Any help would be appreciated.

I did look at Issue #47 from the past which looks like someone was having the same issue, I Added the options in the constructor like they suggested, but that didn't help.

**Comment by burakoner** [comment]
Hi. Could you please share your request and raw response as below

```csharp
var api = new OkxRestApiClient(new OkxRestApiOptions
{
  RawResponse = true,
});

var trade = await api.Trading.PlaceOrderAsync(...)
// send me trade.Raw property value```

**Comment by javedwahid** [comment]
This is what came back: 

{"msg":"Timestamp request expired","code":"50102"}

**Comment by burakoner** [comment]
It is caused by your computer's clock. There is actually no difference between v2.4.8 and v5.4.1217 in terms of the timestamp used in authorization. However, in version 5.4.1219 I enabled a time synchronization algorithm and fixed this problem even if your computer's clock is wrong. You can check links below. Thank you for sharing this issue.

https://github.com/burakoner/OKX.Api/commit/597e35ffe64aec8ea83271225565b15d6995e7a3
https://github.com/burakoner/OKX.Api/releases/tag/5.4.1219
https://www.nuget.org/packages/OKX.Api/5.4.1219

**Comment by javedwahid** [comment]
That worked.  Thank you very much.
